environment: prod

deployment:
  image:
    tag: 0
  replicas: 1
  env:
    redis_host: master.galaxy-prod-elascache-rep-group.mownnt.use1.cache.amazonaws.com

secret:
  redis_pass: automate-all-the-things-prod
